/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_payload_users_roles = pgEnum("enum_payload_users_roles", [
  "super-admin",
  "admin",
  "editor",
  "user",
]);
export const enum_members_social_links_platform = pgEnum(
  "enum_members_social_links_platform",
  ["instagram", "linkedin", "github", "website"],
);
export const enum_members_department = pgEnum("enum_members_department", [
  "cse",
  "ece",
  "eee",
  "ice",
  "me",
  "mme",
  "pe",
  "ce",
  "ch",
]);
export const enum_membership_study_year = pgEnum("enum_membership_study_year", [
  "year1",
  "year2",
  "year3",
  "year4",
]);
export const enum_teams_layout = pgEnum("enum_teams_layout", [
  "grid",
  "inline",
]);

export const payload_users_sessions = pgTable(
  "payload_users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("payload_users_sessions_order_idx").on(columns._order),
    index("payload_users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_users.id],
      name: "payload_users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_users = pgTable(
  "payload_users",
  {
    id: serial("id").primaryKey(),
    roles: enum_payload_users_roles("roles").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    username: varchar("username").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("payload_users_updated_at_idx").on(columns.updatedAt),
    index("payload_users_created_at_idx").on(columns.createdAt),
    uniqueIndex("payload_users_email_idx").on(columns.email),
    uniqueIndex("payload_users_username_idx").on(columns.username),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
  ],
);

export const members_social_links = pgTable(
  "members_social_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    platform: enum_members_social_links_platform("platform").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("members_social_links_order_idx").on(columns._order),
    index("members_social_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [members.id],
      name: "members_social_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const members = pgTable(
  "members",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    profilePicture: integer("profile_picture_id").references(
      () => team_media.id,
      {
        onDelete: "set null",
      },
    ),
    department: enum_members_department("department").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("members_profile_picture_idx").on(columns.profilePicture),
    index("members_updated_at_idx").on(columns.updatedAt),
    index("members_created_at_idx").on(columns.createdAt),
  ],
);

export const membership = pgTable(
  "membership",
  {
    id: serial("id").primaryKey(),
    member: integer("member_id")
      .notNull()
      .references(() => members.id, {
        onDelete: "set null",
      }),
    team: integer("team_id")
      .notNull()
      .references(() => teams.id, {
        onDelete: "set null",
      }),
    role: integer("role_id")
      .notNull()
      .references(() => roles.id, {
        onDelete: "set null",
      }),
    year: integer("year_id")
      .notNull()
      .references(() => year.id, {
        onDelete: "set null",
      }),
    studyYear: enum_membership_study_year("study_year").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("membership_member_idx").on(columns.member),
    index("membership_team_idx").on(columns.team),
    index("membership_role_idx").on(columns.role),
    index("membership_year_idx").on(columns.year),
    index("membership_updated_at_idx").on(columns.updatedAt),
    index("membership_created_at_idx").on(columns.createdAt),
  ],
);

export const roles = pgTable(
  "roles",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    displayOrder: numeric("display_order", { mode: "number" }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("roles_updated_at_idx").on(columns.updatedAt),
    index("roles_created_at_idx").on(columns.createdAt),
  ],
);

export const teams = pgTable(
  "teams",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    teamLogo: integer("team_logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    displayOrder: numeric("display_order", { mode: "number" }).notNull(),
    layout: enum_teams_layout("layout").notNull().default("grid"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("teams_team_logo_idx").on(columns.teamLogo),
    index("teams_updated_at_idx").on(columns.updatedAt),
    index("teams_created_at_idx").on(columns.createdAt),
  ],
);

export const year = pgTable(
  "year",
  {
    id: serial("id").primaryKey(),
    label: varchar("label").notNull(),
    startYear: numeric("start_year", { mode: "number" }).notNull(),
    endYear: numeric("end_year", { mode: "number" }).notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("year_updated_at_idx").on(columns.updatedAt),
    index("year_created_at_idx").on(columns.createdAt),
  ],
);

export const team_media = pgTable(
  "team_media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    "sizes_member-card_url": varchar("sizes_member_card_url"),
    "sizes_member-card_width": numeric("sizes_member_card_width", {
      mode: "number",
    }),
    "sizes_member-card_height": numeric("sizes_member_card_height", {
      mode: "number",
    }),
    "sizes_member-card_mimeType": varchar("sizes_member_card_mime_type"),
    "sizes_member-card_filesize": numeric("sizes_member_card_filesize", {
      mode: "number",
    }),
    "sizes_member-card_filename": varchar("sizes_member_card_filename"),
  },
  (columns) => [
    index("team_media_updated_at_idx").on(columns.updatedAt),
    index("team_media_created_at_idx").on(columns.createdAt),
    uniqueIndex("team_media_filename_idx").on(columns.filename),
    index("team_media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("team_media_sizes_member_card_sizes_member_card_filename_idx").on(
      columns["sizes_member-card_filename"],
    ),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    enabled: boolean("enabled").notNull().default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const site_media = pgTable(
  "site_media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_logo_url: varchar("sizes_logo_url"),
    sizes_logo_width: numeric("sizes_logo_width", { mode: "number" }),
    sizes_logo_height: numeric("sizes_logo_height", { mode: "number" }),
    sizes_logo_mimeType: varchar("sizes_logo_mime_type"),
    sizes_logo_filesize: numeric("sizes_logo_filesize", { mode: "number" }),
    sizes_logo_filename: varchar("sizes_logo_filename"),
  },
  (columns) => [
    index("site_media_updated_at_idx").on(columns.updatedAt),
    index("site_media_created_at_idx").on(columns.createdAt),
    uniqueIndex("site_media_filename_idx").on(columns.filename),
    index("site_media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("site_media_sizes_logo_sizes_logo_filename_idx").on(
      columns.sizes_logo_filename,
    ),
  ],
);

export const about_us_media = pgTable(
  "about_us_media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
  },
  (columns) => [
    index("about_us_media_updated_at_idx").on(columns.updatedAt),
    index("about_us_media_created_at_idx").on(columns.createdAt),
    uniqueIndex("about_us_media_filename_idx").on(columns.filename),
    index("about_us_media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "payload-usersID": integer("payload_users_id"),
    mediaID: integer("media_id"),
    membersID: integer("members_id"),
    membershipID: integer("membership_id"),
    rolesID: integer("roles_id"),
    teamsID: integer("teams_id"),
    yearID: integer("year_id"),
    "team-mediaID": integer("team_media_id"),
    pagesID: integer("pages_id"),
    "site-mediaID": integer("site_media_id"),
    "about-us-mediaID": integer("about_us_media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_payload_users_id_idx").on(
      columns["payload-usersID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_members_id_idx").on(columns.membersID),
    index("payload_locked_documents_rels_membership_id_idx").on(
      columns.membershipID,
    ),
    index("payload_locked_documents_rels_roles_id_idx").on(columns.rolesID),
    index("payload_locked_documents_rels_teams_id_idx").on(columns.teamsID),
    index("payload_locked_documents_rels_year_id_idx").on(columns.yearID),
    index("payload_locked_documents_rels_team_media_id_idx").on(
      columns["team-mediaID"],
    ),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_site_media_id_idx").on(
      columns["site-mediaID"],
    ),
    index("payload_locked_documents_rels_about_us_media_id_idx").on(
      columns["about-us-mediaID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-usersID"]],
      foreignColumns: [payload_users.id],
      name: "payload_locked_documents_rels_payload_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["membersID"]],
      foreignColumns: [members.id],
      name: "payload_locked_documents_rels_members_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["membershipID"]],
      foreignColumns: [membership.id],
      name: "payload_locked_documents_rels_membership_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["rolesID"]],
      foreignColumns: [roles.id],
      name: "payload_locked_documents_rels_roles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["teamsID"]],
      foreignColumns: [teams.id],
      name: "payload_locked_documents_rels_teams_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["yearID"]],
      foreignColumns: [year.id],
      name: "payload_locked_documents_rels_year_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["team-mediaID"]],
      foreignColumns: [team_media.id],
      name: "payload_locked_documents_rels_team_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["site-mediaID"]],
      foreignColumns: [site_media.id],
      name: "payload_locked_documents_rels_site_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["about-us-mediaID"]],
      foreignColumns: [about_us_media.id],
      name: "payload_locked_documents_rels_about_us_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "payload-usersID": integer("payload_users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_payload_users_id_idx").on(
      columns["payload-usersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-usersID"]],
      foreignColumns: [payload_users.id],
      name: "payload_preferences_rels_payload_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_payload_users_sessions = relations(
  payload_users_sessions,
  ({ one }) => ({
    _parentID: one(payload_users, {
      fields: [payload_users_sessions._parentID],
      references: [payload_users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_payload_users = relations(payload_users, ({ many }) => ({
  sessions: many(payload_users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_members_social_links = relations(
  members_social_links,
  ({ one }) => ({
    _parentID: one(members, {
      fields: [members_social_links._parentID],
      references: [members.id],
      relationName: "socialLinks",
    }),
  }),
);
export const relations_members = relations(members, ({ one, many }) => ({
  profilePicture: one(team_media, {
    fields: [members.profilePicture],
    references: [team_media.id],
    relationName: "profilePicture",
  }),
  socialLinks: many(members_social_links, {
    relationName: "socialLinks",
  }),
}));
export const relations_membership = relations(membership, ({ one }) => ({
  member: one(members, {
    fields: [membership.member],
    references: [members.id],
    relationName: "member",
  }),
  team: one(teams, {
    fields: [membership.team],
    references: [teams.id],
    relationName: "team",
  }),
  role: one(roles, {
    fields: [membership.role],
    references: [roles.id],
    relationName: "role",
  }),
  year: one(year, {
    fields: [membership.year],
    references: [year.id],
    relationName: "year",
  }),
}));
export const relations_roles = relations(roles, () => ({}));
export const relations_teams = relations(teams, ({ one }) => ({
  teamLogo: one(media, {
    fields: [teams.teamLogo],
    references: [media.id],
    relationName: "teamLogo",
  }),
}));
export const relations_year = relations(year, () => ({}));
export const relations_team_media = relations(team_media, () => ({}));
export const relations_pages = relations(pages, () => ({}));
export const relations_site_media = relations(site_media, () => ({}));
export const relations_about_us_media = relations(about_us_media, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    "payload-usersID": one(payload_users, {
      fields: [payload_locked_documents_rels["payload-usersID"]],
      references: [payload_users.id],
      relationName: "payload-users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    membersID: one(members, {
      fields: [payload_locked_documents_rels.membersID],
      references: [members.id],
      relationName: "members",
    }),
    membershipID: one(membership, {
      fields: [payload_locked_documents_rels.membershipID],
      references: [membership.id],
      relationName: "membership",
    }),
    rolesID: one(roles, {
      fields: [payload_locked_documents_rels.rolesID],
      references: [roles.id],
      relationName: "roles",
    }),
    teamsID: one(teams, {
      fields: [payload_locked_documents_rels.teamsID],
      references: [teams.id],
      relationName: "teams",
    }),
    yearID: one(year, {
      fields: [payload_locked_documents_rels.yearID],
      references: [year.id],
      relationName: "year",
    }),
    "team-mediaID": one(team_media, {
      fields: [payload_locked_documents_rels["team-mediaID"]],
      references: [team_media.id],
      relationName: "team-media",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    "site-mediaID": one(site_media, {
      fields: [payload_locked_documents_rels["site-mediaID"]],
      references: [site_media.id],
      relationName: "site-media",
    }),
    "about-us-mediaID": one(about_us_media, {
      fields: [payload_locked_documents_rels["about-us-mediaID"]],
      references: [about_us_media.id],
      relationName: "about-us-media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    "payload-usersID": one(payload_users, {
      fields: [payload_preferences_rels["payload-usersID"]],
      references: [payload_users.id],
      relationName: "payload-users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_payload_users_roles: typeof enum_payload_users_roles;
  enum_members_social_links_platform: typeof enum_members_social_links_platform;
  enum_members_department: typeof enum_members_department;
  enum_membership_study_year: typeof enum_membership_study_year;
  enum_teams_layout: typeof enum_teams_layout;
  payload_users_sessions: typeof payload_users_sessions;
  payload_users: typeof payload_users;
  media: typeof media;
  members_social_links: typeof members_social_links;
  members: typeof members;
  membership: typeof membership;
  roles: typeof roles;
  teams: typeof teams;
  year: typeof year;
  team_media: typeof team_media;
  pages: typeof pages;
  site_media: typeof site_media;
  about_us_media: typeof about_us_media;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_payload_users_sessions: typeof relations_payload_users_sessions;
  relations_payload_users: typeof relations_payload_users;
  relations_media: typeof relations_media;
  relations_members_social_links: typeof relations_members_social_links;
  relations_members: typeof relations_members;
  relations_membership: typeof relations_membership;
  relations_roles: typeof relations_roles;
  relations_teams: typeof relations_teams;
  relations_year: typeof relations_year;
  relations_team_media: typeof relations_team_media;
  relations_pages: typeof relations_pages;
  relations_site_media: typeof relations_site_media;
  relations_about_us_media: typeof relations_about_us_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
